<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>traversability_mapping</name>
  <version>0.1.0</version>
  <description>
    Traversability mapping algorithms and planner plugin for ROS 2 Humble.
  </description>

  <maintainer email="yanzhijie@buaa.edu.cn">yanzj</maintainer>
  <license>BSD</license>

  <!-- build tool -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- C++ client library -->
  <depend>rclcpp</depend>

  <!-- <depend>rclpy</depend> -->

  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>elevation_msgs</depend>

  <!-- TF2 -->
  <depend>tf2_ros</depend>

  <!-- PCL and OpenCV -->
  <depend>pcl_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>cv_bridge</depend>
  <depend>image_transport</depend>

  <!-- interactive markers -->
  <depend>interactive_markers</depend>

  <!-- insert plugin lib -->
  <depend>pluginlib</depend>
  <depend>nav_core</depend>

  <export>
    <!-- export nav_core Planner Plugin XML -->
    <pluginlib plugin="${prefix}/share/${PROJECT_NAME}/tm_planner_plugin.xml"/>
  </export>
</package>